### ISSUE TITLE
Build errors 

### ISSUE THREAD

**Issue by brittAnderson** [rmculpepper/gamble#26]
Tried to install this a few days ago and got error messages. I believe they are mostly documentation. If this package is still being actively maintained I could file a detailed report on the message, but I thought I would check the status first. Really anxious to try Racket for some probabilistic models and use in teaching, so I am anxious to learn if packages like this and drbayes are going to endure. Thanks.

**Comment by rmculpepper** [comment]
I'm no longer actively developing this package. I have plans to split it into smaller (hopefully, more reliable) pieces, but that's on hold for the moment. On the other than, if the current errors are simple to fix, I'll try to do that, but I might not get to it this week.

**Comment by brittAnderson** [comment]
For future reference here are the errors from installing on 8.0. They only seem to be in the tests and examples and so do not prevent the installation. I will see if I can come to understand how to fix them as I play with your package. I will close for now, but just leave this as a record. 

    error: during making for <pkgs>/gamble/gamble/examples
      gamble/examples/par-pf-airplane-model.rkt:86:11: observe: expression is not observable;
       it does not sample in an observable context
        at: (observed-altimeter-reading p terrain)
        in: (observe (observed-altimeter-reading p terrain) observed-alt)
        compiling: <pkgs>/gamble/gamble/examples/par-pf-airplane-model.rkt
    error: during making for <pkgs>/gamble/gamble/examples
      gamble/examples/par-pf-airplane-model.rkt:86:11: observe: expression is not observable;
       it does not sample in an observable context
        at: (observed-altimeter-reading p terrain)
        in: (observe (observed-altimeter-reading p terrain) observed-alt)
        compiling: <pkgs>/gamble/gamble/examples/par-pf-airplane-sim.rkt
    error: during making for <pkgs>/gamble/gamble/examples
      gamble/examples/pf-airplane.rkt:87:11: observe: expression is not observable;
       it does not sample in an observable context
        at: (observed-altimeter-reading p terrain)
        in: (observe (observed-altimeter-reading p terrain) observed-alt)
        compiling: <pkgs>/gamble/gamble/examples/pf-airplane.rkt
    error: during making for <pkgs>/gamble/gamble/tests
      gamble/private/instrument.rkt:341:33: pred: use does not match pattern: (pred y a)
        in: (pred obs-v)
        compiling: <pkgs>/gamble/gamble/tests/observe.rkt
